logging:
  level:
    org.springframework.web: INFO
    com.community: DEBUG

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

spring:
  profiles:
    active: local
  application:
    name: community-platform
  datasource:
    url: jdbc:mysql://${community.mysql.ip}:${community.mysql.port}/${community.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&connectionCollation=utf8mb4_unicode_ci
    username: ${community.mysql.username}
    password: ${community.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: ${community.redis.host}
      port: ${community.redis.port}
      database: 0
      timeout: 1800000
      password: ${community.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  elasticsearch:
    uris: ${community.es.uris}

rocketmq:
  name-server: ${rocketmq.name-server}
  producer:
    group: community-producer
    send-message-timeout: 3000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 2
    retry-next-server: false
  consumer:
    group: community-consumer

oss:
  enabled: true
  type: minio
  endpoint: ${community.minio.endpoint}
  access-key: ${community.minio.access-key}
  secret-key: ${community.minio.secret-key}
  bucket-name: ${community.minio.bucket}

wx:
  mp:
    callback: ${community.wx.callback}
    configs:
      - appId: ${community.wx.appId}
        secret: ${community.wx.secret}
        token: ${community.wx.token}
        aesKey: ${community.wx.aesKey}

community:
  jwt:
    secret: ${community.jwt.secret}
  websocket:
    port: 8091
